
name: Laravel CI

on:
  push:
    branches: [ 'main']
  pull_request:
    branches: [ 'main' ]
    types: [opened, synchronize]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar Código
      uses: actions/checkout@v4

    - name: Configurar PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2' # Cambia a tu versión de PHP
        extensions: mbstring, xml, ctype, iconv, json, sqlite3, pdo_sqlite
        coverage: none

    - name: Copiar Archivo de Entorno
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Instalar Dependencias de Composer
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generar Clave de Aplicación
      run: php artisan key:generate

    - name: Configurar Directorios de Permisos
      run: chmod -R 777 storage bootstrap/cache

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit --progress=false

    - name: Building de la aplicacion
      run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: public/build

    - name: Ejecutar Pruebas (SQLite)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: |
        php artisan migrate --seed
        php artisan test




    